include $(shell Makefile.venv)

#VENV_NAME?=venv
#VENV_ACTIVATE=. $(VENV_NAME)/bin/activate
#PYTHON=${VENV_NAME}/bin/python3
 PYTHON=/usr/bin/python3.8

install: requirements.txt 
#install packages
	pip install -r requirements.txt